"""initial schema

Revision ID: 4e06934ab2d0
Revises: 
Create Date: 2026-06-29 04:09:18.945777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e06934ab2d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aigc_suggestion', schema=None) as batch_op:
        batch_op.create_index('idx_suggestion_status_created', ['status', 'created_at'], unique=False)

    with op.batch_alter_table('erp_stock_move', schema=None) as batch_op:
        batch_op.create_index('idx_stockmove_product_warehouse', ['product_id', 'warehouse_id'], unique=False)
        batch_op.create_index('idx_stockmove_type_date', ['move_type', 'created_at'], unique=False)

    with op.batch_alter_table('ext_ecommerce_order', schema=None) as batch_op:
        batch_op.create_index('idx_extorder_synced_platform', ['synced', 'platform'], unique=False)

    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('ext_ecommerce_order', schema=None) as batch_op:
        batch_op.drop_index('idx_extorder_synced_platform')

    with op.batch_alter_table('erp_stock_move', schema=None) as batch_op:
        batch_op.drop_index('idx_stockmove_type_date')
        batch_op.drop_index('idx_stockmove_product_warehouse')

    with op.batch_alter_table('aigc_suggestion', schema=None) as batch_op:
        batch_op.drop_index('idx_suggestion_status_created')

    # ### end Alembic commands ###
